version: '3.3'

services:
    exceptionbundle_php:
        image: dh.rinsvent.ru/php8dev
        container_name: exceptionbundle_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 0
            PHP_IDE_CONFIG: "serverName=exceptionbundle_php"

networks:
    default:
        external:
            name: full-project
