services:
  _defaults:
    autoconfigure: true
    public: false
    autowire: true


  Rinsvent\ExceptionBundle\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,ExceptionBundle.php}'